#-------------------------------------------------
#
# Project created by QtCreator 2021-03-16T09:12:12
#
#-------------------------------------------------

QT       += sql widgets

TARGET = ilwiscore
TEMPLATE = lib

include(../global.pri)

QT += widgets

DEFINES += CORE_LIBRARY


# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
# DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

linux {
    target.path = /usr/lib
    INSTALLS += target
}

HEADERS += \
   include/catalog/catalog.h \
   include/catalog/catalogconnector.h \
   include/catalog/catalogexplorer.h \
   include/catalog/catalogexplorerworker.h \
   include/catalog/catalogitem.h \
   include/catalog/catalogquery.h \
   include/catalog/catalogview.h \
   include/catalog/dataformat.h \
   include/catalog/dataset.h \
   include/catalog/foldercatalogexplorer.h \
   include/catalog/folderconnector.h \
   include/catalog/mastercatalog.h \
   include/catalog/mastercatalogcache.h \
   include/catalog/resource.h \
   include/geos/include/geos/algorithm/distance/DiscreteHausdorffDistance.h \
   include/geos/include/geos/algorithm/distance/DistanceToPoint.h \
   include/geos/include/geos/algorithm/distance/PointPairDistance.h \
   include/geos/include/geos/algorithm/locate/IndexedPointInAreaLocator.h \
   include/geos/include/geos/algorithm/locate/PointOnGeometryLocator.h \
   include/geos/include/geos/algorithm/locate/SimplePointInAreaLocator.h \
   include/geos/include/geos/algorithm/Angle.h \
   include/geos/include/geos/algorithm/BoundaryNodeRule.h \
   include/geos/include/geos/algorithm/CentralEndpointIntersector.h \
   include/geos/include/geos/algorithm/Centroid.h \
   include/geos/include/geos/algorithm/CentroidArea.h \
   include/geos/include/geos/algorithm/CentroidLine.h \
   include/geos/include/geos/algorithm/CentroidPoint.h \
   include/geos/include/geos/algorithm/CGAlgorithms.h \
   include/geos/include/geos/algorithm/ConvexHull.h \
   include/geos/include/geos/algorithm/HCoordinate.h \
   include/geos/include/geos/algorithm/InteriorPointArea.h \
   include/geos/include/geos/algorithm/InteriorPointLine.h \
   include/geos/include/geos/algorithm/InteriorPointPoint.h \
   include/geos/include/geos/algorithm/LineIntersector.h \
   include/geos/include/geos/algorithm/MCPointInRing.h \
   include/geos/include/geos/algorithm/MinimumDiameter.h \
   include/geos/include/geos/algorithm/NotRepresentableException.h \
   include/geos/include/geos/algorithm/PointInRing.h \
   include/geos/include/geos/algorithm/PointLocator.h \
   include/geos/include/geos/algorithm/RayCrossingCounter.h \
   include/geos/include/geos/algorithm/RobustDeterminant.h \
   include/geos/include/geos/algorithm/SimplePointInRing.h \
   include/geos/include/geos/algorithm/SIRtreePointInRing.h \
   include/geos/include/geos/geom/prep/AbstractPreparedPolygonContains.h \
   include/geos/include/geos/geom/prep/BasicPreparedGeometry.h \
   include/geos/include/geos/geom/prep/PreparedGeometry.h \
   include/geos/include/geos/geom/prep/PreparedGeometryFactory.h \
   include/geos/include/geos/geom/prep/PreparedLineString.h \
   include/geos/include/geos/geom/prep/PreparedLineStringIntersects.h \
   include/geos/include/geos/geom/prep/PreparedPoint.h \
   include/geos/include/geos/geom/prep/PreparedPolygon.h \
   include/geos/include/geos/geom/prep/PreparedPolygonContains.h \
   include/geos/include/geos/geom/prep/PreparedPolygonContainsProperly.h \
   include/geos/include/geos/geom/prep/PreparedPolygonCovers.h \
   include/geos/include/geos/geom/prep/PreparedPolygonIntersects.h \
   include/geos/include/geos/geom/prep/PreparedPolygonPredicate.h \
   include/geos/include/geos/geom/util/ComponentCoordinateExtracter.h \
   include/geos/include/geos/geom/util/CoordinateOperation.h \
   include/geos/include/geos/geom/util/GeometryCombiner.h \
   include/geos/include/geos/geom/util/GeometryEditor.h \
   include/geos/include/geos/geom/util/GeometryEditorOperation.h \
   include/geos/include/geos/geom/util/GeometryExtracter.h \
   include/geos/include/geos/geom/util/GeometryTransformer.h \
   include/geos/include/geos/geom/util/LinearComponentExtracter.h \
   include/geos/include/geos/geom/util/PointExtracter.h \
   include/geos/include/geos/geom/util/PolygonExtracter.h \
   include/geos/include/geos/geom/util/ShortCircuitedGeometryVisitor.h \
   include/geos/include/geos/geom/util/SineStarFactory.h \
   include/geos/include/geos/geom/BinaryOp.h \
   include/geos/include/geos/geom/Coordinate.h \
   include/geos/include/geos/geom/CoordinateArraySequence.h \
   include/geos/include/geos/geom/CoordinateArraySequenceFactory.h \
   include/geos/include/geos/geom/CoordinateFilter.h \
   include/geos/include/geos/geom/CoordinateList.h \
   include/geos/include/geos/geom/CoordinateSequence.h \
   include/geos/include/geos/geom/CoordinateSequenceFactory.h \
   include/geos/include/geos/geom/CoordinateSequenceFilter.h \
   include/geos/include/geos/geom/Dimension.h \
   include/geos/include/geos/geom/Envelope.h \
   include/geos/include/geos/geom/Geometry.h \
   include/geos/include/geos/geom/GeometryCollection.h \
   include/geos/include/geos/geom/GeometryComponentFilter.h \
   include/geos/include/geos/geom/GeometryFactory.h \
   include/geos/include/geos/geom/GeometryFilter.h \
   include/geos/include/geos/geom/GeometryList.h \
   include/geos/include/geos/geom/IntersectionMatrix.h \
   include/geos/include/geos/geom/Lineal.h \
   include/geos/include/geos/geom/LinearRing.h \
   include/geos/include/geos/geom/LineSegment.h \
   include/geos/include/geos/geom/LineString.h \
   include/geos/include/geos/geom/Location.h \
   include/geos/include/geos/geom/MultiLineString.h \
   include/geos/include/geos/geom/MultiPoint.h \
   include/geos/include/geos/geom/MultiPolygon.h \
   include/geos/include/geos/geom/Point.h \
   include/geos/include/geos/geom/Polygon.h \
   include/geos/include/geos/geom/Polygonal.h \
   include/geos/include/geos/geom/PrecisionModel.h \
   include/geos/include/geos/geom/Puntal.h \
   include/geos/include/geos/geom/Triangle.h \
   include/geos/include/geos/geomgraph/index/EdgeSetIntersector.h \
   include/geos/include/geos/geomgraph/index/MonotoneChain.h \
   include/geos/include/geos/geomgraph/index/MonotoneChainEdge.h \
   include/geos/include/geos/geomgraph/index/MonotoneChainIndexer.h \
   include/geos/include/geos/geomgraph/index/SegmentIntersector.h \
   include/geos/include/geos/geomgraph/index/SimpleEdgeSetIntersector.h \
   include/geos/include/geos/geomgraph/index/SimpleMCSweepLineIntersector.h \
   include/geos/include/geos/geomgraph/index/SimpleSweepLineIntersector.h \
   include/geos/include/geos/geomgraph/index/SweepLineEvent.h \
   include/geos/include/geos/geomgraph/index/SweepLineEventObj.h \
   include/geos/include/geos/geomgraph/index/SweepLineSegment.h \
   include/geos/include/geos/geomgraph/Depth.h \
   include/geos/include/geos/geomgraph/DirectedEdge.h \
   include/geos/include/geos/geomgraph/DirectedEdgeStar.h \
   include/geos/include/geos/geomgraph/Edge.h \
   include/geos/include/geos/geomgraph/EdgeEnd.h \
   include/geos/include/geos/geomgraph/EdgeEndStar.h \
   include/geos/include/geos/geomgraph/EdgeIntersection.h \
   include/geos/include/geos/geomgraph/EdgeIntersectionList.h \
   include/geos/include/geos/geomgraph/EdgeList.h \
   include/geos/include/geos/geomgraph/EdgeNodingValidator.h \
   include/geos/include/geos/geomgraph/EdgeRing.h \
   include/geos/include/geos/geomgraph/GeometryGraph.h \
   include/geos/include/geos/geomgraph/GraphComponent.h \
   include/geos/include/geos/geomgraph/Label.h \
   include/geos/include/geos/geomgraph/Node.h \
   include/geos/include/geos/geomgraph/NodeFactory.h \
   include/geos/include/geos/geomgraph/NodeMap.h \
   include/geos/include/geos/geomgraph/PlanarGraph.h \
   include/geos/include/geos/geomgraph/Position.h \
   include/geos/include/geos/geomgraph/Quadrant.h \
   include/geos/include/geos/geomgraph/TopologyLocation.h \
   include/geos/include/geos/index/bintree/Bintree.h \
   include/geos/include/geos/index/bintree/Interval.h \
   include/geos/include/geos/index/bintree/Key.h \
   include/geos/include/geos/index/bintree/Node.h \
   include/geos/include/geos/index/bintree/NodeBase.h \
   include/geos/include/geos/index/bintree/Root.h \
   include/geos/include/geos/index/chain/MonotoneChain.h \
   include/geos/include/geos/index/chain/MonotoneChainBuilder.h \
   include/geos/include/geos/index/chain/MonotoneChainOverlapAction.h \
   include/geos/include/geos/index/chain/MonotoneChainSelectAction.h \
   include/geos/include/geos/index/intervalrtree/IntervalRTreeBranchNode.h \
   include/geos/include/geos/index/intervalrtree/IntervalRTreeLeafNode.h \
   include/geos/include/geos/index/intervalrtree/IntervalRTreeNode.h \
   include/geos/include/geos/index/intervalrtree/SortedPackedIntervalRTree.h \
   include/geos/include/geos/index/quadtree/DoubleBits.h \
   include/geos/include/geos/index/quadtree/IntervalSize.h \
   include/geos/include/geos/index/quadtree/Key.h \
   include/geos/include/geos/index/quadtree/Node.h \
   include/geos/include/geos/index/quadtree/NodeBase.h \
   include/geos/include/geos/index/quadtree/Quadtree.h \
   include/geos/include/geos/index/quadtree/Root.h \
   include/geos/include/geos/index/strtree/AbstractNode.h \
   include/geos/include/geos/index/strtree/AbstractSTRtree.h \
   include/geos/include/geos/index/strtree/Boundable.h \
   include/geos/include/geos/index/strtree/Interval.h \
   include/geos/include/geos/index/strtree/ItemBoundable.h \
   include/geos/include/geos/index/strtree/SIRtree.h \
   include/geos/include/geos/index/strtree/STRtree.h \
   include/geos/include/geos/index/sweepline/SweepLineEvent.h \
   include/geos/include/geos/index/sweepline/SweepLineIndex.h \
   include/geos/include/geos/index/sweepline/SweepLineInterval.h \
   include/geos/include/geos/index/sweepline/SweepLineOverlapAction.h \
   include/geos/include/geos/index/ItemVisitor.h \
   include/geos/include/geos/index/SpatialIndex.h \
   include/geos/include/geos/io/ByteOrderDataInStream.h \
   include/geos/include/geos/io/ByteOrderValues.h \
   include/geos/include/geos/io/CLocalizer.h \
   include/geos/include/geos/io/ParseException.h \
   include/geos/include/geos/io/StringTokenizer.h \
   include/geos/include/geos/io/WKBConstants.h \
   include/geos/include/geos/io/WKBReader.h \
   include/geos/include/geos/io/WKBWriter.h \
   include/geos/include/geos/io/WKTReader.h \
   include/geos/include/geos/io/WKTWriter.h \
   include/geos/include/geos/io/Writer.h \
   include/geos/include/geos/linearref/ExtractLineByLocation.h \
   include/geos/include/geos/linearref/LengthIndexedLine.h \
   include/geos/include/geos/linearref/LengthIndexOfPoint.h \
   include/geos/include/geos/linearref/LengthLocationMap.h \
   include/geos/include/geos/linearref/LinearGeometryBuilder.h \
   include/geos/include/geos/linearref/LinearIterator.h \
   include/geos/include/geos/linearref/LinearLocation.h \
   include/geos/include/geos/linearref/LocationIndexedLine.h \
   include/geos/include/geos/linearref/LocationIndexOfLine.h \
   include/geos/include/geos/linearref/LocationIndexOfPoint.h \
   include/geos/include/geos/noding/snapround/HotPixel.h \
   include/geos/include/geos/noding/snapround/MCIndexPointSnapper.h \
   include/geos/include/geos/noding/snapround/MCIndexSnapRounder.h \
   include/geos/include/geos/noding/snapround/SimpleSnapRounder.h \
   include/geos/include/geos/noding/BasicSegmentString.h \
   include/geos/include/geos/noding/FastNodingValidator.h \
   include/geos/include/geos/noding/FastSegmentSetIntersectionFinder.h \
   include/geos/include/geos/noding/GeometryNoder.h \
   include/geos/include/geos/noding/IntersectionAdder.h \
   include/geos/include/geos/noding/IntersectionFinderAdder.h \
   include/geos/include/geos/noding/IteratedNoder.h \
   include/geos/include/geos/noding/MCIndexNoder.h \
   include/geos/include/geos/noding/MCIndexSegmentSetMutualIntersector.h \
   include/geos/include/geos/noding/NodableSegmentString.h \
   include/geos/include/geos/noding/NodedSegmentString.h \
   include/geos/include/geos/noding/Noder.h \
   include/geos/include/geos/noding/NodingValidator.h \
   include/geos/include/geos/noding/Octant.h \
   include/geos/include/geos/noding/OrientedCoordinateArray.h \
   include/geos/include/geos/noding/ScaledNoder.h \
   include/geos/include/geos/noding/SegmentIntersectionDetector.h \
   include/geos/include/geos/noding/SegmentIntersector.h \
   include/geos/include/geos/noding/SegmentNode.h \
   include/geos/include/geos/noding/SegmentNodeList.h \
   include/geos/include/geos/noding/SegmentPointComparator.h \
   include/geos/include/geos/noding/SegmentSetMutualIntersector.h \
   include/geos/include/geos/noding/SegmentString.h \
   include/geos/include/geos/noding/SegmentStringUtil.h \
   include/geos/include/geos/noding/SimpleNoder.h \
   include/geos/include/geos/noding/SingleInteriorIntersectionFinder.h \
   include/geos/include/geos/noding/SinglePassNoder.h \
   include/geos/include/geos/operation/buffer/BufferBuilder.h \
   include/geos/include/geos/operation/buffer/BufferInputLineSimplifier.h \
   include/geos/include/geos/operation/buffer/BufferOp.h \
   include/geos/include/geos/operation/buffer/BufferParameters.h \
   include/geos/include/geos/operation/buffer/BufferSubgraph.h \
   include/geos/include/geos/operation/buffer/OffsetCurveBuilder.h \
   include/geos/include/geos/operation/buffer/OffsetCurveSetBuilder.h \
   include/geos/include/geos/operation/buffer/OffsetSegmentGenerator.h \
   include/geos/include/geos/operation/buffer/OffsetSegmentString.h \
   include/geos/include/geos/operation/buffer/RightmostEdgeFinder.h \
   include/geos/include/geos/operation/buffer/SubgraphDepthLocater.h \
   include/geos/include/geos/operation/distance/ConnectedElementLocationFilter.h \
   include/geos/include/geos/operation/distance/ConnectedElementPointFilter.h \
   include/geos/include/geos/operation/distance/DistanceOp.h \
   include/geos/include/geos/operation/distance/GeometryLocation.h \
   include/geos/include/geos/operation/intersection/Rectangle.h \
   include/geos/include/geos/operation/intersection/RectangleIntersection.h \
   include/geos/include/geos/operation/intersection/RectangleIntersectionBuilder.h \
   include/geos/include/geos/operation/linemerge/EdgeString.h \
   include/geos/include/geos/operation/linemerge/LineMergeDirectedEdge.h \
   include/geos/include/geos/operation/linemerge/LineMergeEdge.h \
   include/geos/include/geos/operation/linemerge/LineMergeGraph.h \
   include/geos/include/geos/operation/linemerge/LineMerger.h \
   include/geos/include/geos/operation/linemerge/LineSequencer.h \
   include/geos/include/geos/operation/overlay/snap/GeometrySnapper.h \
   include/geos/include/geos/operation/overlay/snap/LineStringSnapper.h \
   include/geos/include/geos/operation/overlay/snap/SnapIfNeededOverlayOp.h \
   include/geos/include/geos/operation/overlay/snap/SnapOverlayOp.h \
   include/geos/include/geos/operation/overlay/validate/FuzzyPointLocator.h \
   include/geos/include/geos/operation/overlay/validate/OffsetPointGenerator.h \
   include/geos/include/geos/operation/overlay/validate/OverlayResultValidator.h \
   include/geos/include/geos/operation/overlay/EdgeSetNoder.h \
   include/geos/include/geos/operation/overlay/ElevationMatrix.h \
   include/geos/include/geos/operation/overlay/ElevationMatrixCell.h \
   include/geos/include/geos/operation/overlay/LineBuilder.h \
   include/geos/include/geos/operation/overlay/MaximalEdgeRing.h \
   include/geos/include/geos/operation/overlay/MinimalEdgeRing.h \
   include/geos/include/geos/operation/overlay/OverlayNodeFactory.h \
   include/geos/include/geos/operation/overlay/OverlayOp.h \
   include/geos/include/geos/operation/overlay/PointBuilder.h \
   include/geos/include/geos/operation/overlay/PolygonBuilder.h \
   include/geos/include/geos/operation/polygonize/EdgeRing.h \
   include/geos/include/geos/operation/polygonize/PolygonizeDirectedEdge.h \
   include/geos/include/geos/operation/polygonize/PolygonizeEdge.h \
   include/geos/include/geos/operation/polygonize/PolygonizeGraph.h \
   include/geos/include/geos/operation/polygonize/Polygonizer.h \
   include/geos/include/geos/operation/predicate/RectangleContains.h \
   include/geos/include/geos/operation/predicate/RectangleIntersects.h \
   include/geos/include/geos/operation/predicate/SegmentIntersectionTester.h \
   include/geos/include/geos/operation/relate/EdgeEndBuilder.h \
   include/geos/include/geos/operation/relate/EdgeEndBundle.h \
   include/geos/include/geos/operation/relate/EdgeEndBundleStar.h \
   include/geos/include/geos/operation/relate/RelateComputer.h \
   include/geos/include/geos/operation/relate/RelateNode.h \
   include/geos/include/geos/operation/relate/RelateNodeFactory.h \
   include/geos/include/geos/operation/relate/RelateNodeGraph.h \
   include/geos/include/geos/operation/relate/RelateOp.h \
   include/geos/include/geos/operation/sharedpaths/SharedPathsOp.h \
   include/geos/include/geos/operation/union/CascadedPolygonUnion.h \
   include/geos/include/geos/operation/union/CascadedUnion.h \
   include/geos/include/geos/operation/union/GeometryListHolder.h \
   include/geos/include/geos/operation/union/PointGeometryUnion.h \
   include/geos/include/geos/operation/union/UnaryUnionOp.h \
   include/geos/include/geos/operation/valid/ConnectedInteriorTester.h \
   include/geos/include/geos/operation/valid/ConsistentAreaTester.h \
   include/geos/include/geos/operation/valid/IsValidOp.h \
   include/geos/include/geos/operation/valid/QuadtreeNestedRingTester.h \
   include/geos/include/geos/operation/valid/RepeatedPointTester.h \
   include/geos/include/geos/operation/valid/SimpleNestedRingTester.h \
   include/geos/include/geos/operation/valid/SweeplineNestedRingTester.h \
   include/geos/include/geos/operation/valid/TopologyValidationError.h \
   include/geos/include/geos/operation/GeometryGraphOperation.h \
   include/geos/include/geos/operation/IsSimpleOp.h \
   include/geos/include/geos/planargraph/algorithm/ConnectedSubgraphFinder.h \
   include/geos/include/geos/planargraph/DirectedEdge.h \
   include/geos/include/geos/planargraph/DirectedEdgeStar.h \
   include/geos/include/geos/planargraph/Edge.h \
   include/geos/include/geos/planargraph/GraphComponent.h \
   include/geos/include/geos/planargraph/Node.h \
   include/geos/include/geos/planargraph/NodeMap.h \
   include/geos/include/geos/planargraph/PlanarGraph.h \
   include/geos/include/geos/planargraph/Subgraph.h \
   include/geos/include/geos/precision/CommonBits.h \
   include/geos/include/geos/precision/CommonBitsOp.h \
   include/geos/include/geos/precision/CommonBitsRemover.h \
   include/geos/include/geos/precision/EnhancedPrecisionOp.h \
   include/geos/include/geos/precision/GeometryPrecisionReducer.h \
   include/geos/include/geos/precision/PrecisionReducerCoordinateOperation.h \
   include/geos/include/geos/precision/SimpleGeometryPrecisionReducer.h \
   include/geos/include/geos/simplify/DouglasPeuckerLineSimplifier.h \
   include/geos/include/geos/simplify/DouglasPeuckerSimplifier.h \
   include/geos/include/geos/simplify/LineSegmentIndex.h \
   include/geos/include/geos/simplify/TaggedLineSegment.h \
   include/geos/include/geos/simplify/TaggedLinesSimplifier.h \
   include/geos/include/geos/simplify/TaggedLineString.h \
   include/geos/include/geos/simplify/TaggedLineStringSimplifier.h \
   include/geos/include/geos/simplify/TopologyPreservingSimplifier.h \
   include/geos/include/geos/triangulate/quadedge/LastFoundQuadEdgeLocator.h \
   include/geos/include/geos/triangulate/quadedge/LocateFailureException.h \
   include/geos/include/geos/triangulate/quadedge/QuadEdge.h \
   include/geos/include/geos/triangulate/quadedge/QuadEdgeLocator.h \
   include/geos/include/geos/triangulate/quadedge/QuadEdgeSubdivision.h \
   include/geos/include/geos/triangulate/quadedge/TrianglePredicate.h \
   include/geos/include/geos/triangulate/quadedge/TriangleVisitor.h \
   include/geos/include/geos/triangulate/quadedge/Vertex.h \
   include/geos/include/geos/triangulate/DelaunayTriangulationBuilder.h \
   include/geos/include/geos/triangulate/IncrementalDelaunayTriangulator.h \
   include/geos/include/geos/triangulate/VoronoiDiagramBuilder.h \
   include/geos/include/geos/util/Assert.h \
   include/geos/include/geos/util/AssertionFailedException.h \
   include/geos/include/geos/util/CoordinateArrayFilter.h \
   include/geos/include/geos/util/GeometricShapeFactory.h \
   include/geos/include/geos/util/GEOSException.h \
   include/geos/include/geos/util/IllegalArgumentException.h \
   include/geos/include/geos/util/IllegalStateException.h \
   include/geos/include/geos/util/Interrupt.h \
   include/geos/include/geos/util/Machine.h \
   include/geos/include/geos/util/math.h \
   include/geos/include/geos/util/TopologyException.h \
   include/geos/include/geos/util/UniqueCoordinateArrayFilter.h \
   include/geos/include/geos/util/UnsupportedOperationException.h \
   include/geos/include/geos/export.h \
   include/geos/include/geos/geom.h \
   include/geos/include/geos/geomgraph.h \
   include/geos/include/geos/geomgraphindex.h \
   include/geos/include/geos/geomUtil.h \
   include/geos/include/geos/geosAlgorithm.h \
   include/geos/include/geos/indexBintree.h \
   include/geos/include/geos/indexChain.h \
   include/geos/include/geos/indexQuadtree.h \
   include/geos/include/geos/indexStrtree.h \
   include/geos/include/geos/indexSweepline.h \
   include/geos/include/geos/inline.h \
   include/geos/include/geos/io.h \
   include/geos/include/geos/noding.h \
   include/geos/include/geos/nodingSnapround.h \
   include/geos/include/geos/opBuffer.h \
   include/geos/include/geos/opDistance.h \
   include/geos/include/geos/operation.h \
   include/geos/include/geos/opLinemerge.h \
   include/geos/include/geos/opOverlay.h \
   include/geos/include/geos/opPolygonize.h \
   include/geos/include/geos/opPredicate.h \
   include/geos/include/geos/opRelate.h \
   include/geos/include/geos/opValid.h \
   include/geos/include/geos/planargraph.h \
   include/geos/include/geos/platform.h \
   include/geos/include/geos/precision.h \
   include/geos/include/geos/profiler.h \
   include/geos/include/geos/spatialIndex.h \
   include/geos/include/geos/timeval.h \
   include/geos/include/geos/unload.h \
   include/geos/include/geos/util.h \
   include/geos/include/geos/version.h \
   include/geos/include/geos.h \
   include/geos/src/operation/valid/IndexedNestedRingTester.h \
   include/ilwisobjects/coverage/basegrid.h \
   include/ilwisobjects/coverage/blockiterator.h \
   include/ilwisobjects/coverage/coverage.h \
   include/ilwisobjects/coverage/feature.h \
   include/ilwisobjects/coverage/featurecoverage.h \
   include/ilwisobjects/coverage/featurefactory.h \
   include/ilwisobjects/coverage/featureiterator.h \
   include/ilwisobjects/coverage/geometryhelper.h \
   include/ilwisobjects/coverage/grid.h \
   include/ilwisobjects/coverage/indexslicer.h \
   include/ilwisobjects/coverage/pixeliterator.h \
   include/ilwisobjects/coverage/raster.h \
   include/ilwisobjects/coverage/rastercoverage.h \
   include/ilwisobjects/coverage/rasterinterpolator.h \
   include/ilwisobjects/coverage/vertexiterator.h \
   include/ilwisobjects/domain/colordomain.h \
   include/ilwisobjects/domain/coloritem.h \
   include/ilwisobjects/domain/colorrange.h \
   include/ilwisobjects/domain/coordinatedomain.h \
   include/ilwisobjects/domain/datadefinition.h \
   include/ilwisobjects/domain/domain.h \
   include/ilwisobjects/domain/domainhelper.h \
   include/ilwisobjects/domain/domainitem.h \
   include/ilwisobjects/domain/domainmerger.h \
   include/ilwisobjects/domain/identifieritem.h \
   include/ilwisobjects/domain/identifierrange.h \
   include/ilwisobjects/domain/interval.h \
   include/ilwisobjects/domain/intervalrange.h \
   include/ilwisobjects/domain/itemdomain.h \
   include/ilwisobjects/domain/itemiterator.h \
   include/ilwisobjects/domain/itemrange.h \
   include/ilwisobjects/domain/numericdomain.h \
   include/ilwisobjects/domain/numericrange.h \
   include/ilwisobjects/domain/rangeiterator.h \
   include/ilwisobjects/domain/textdomain.h \
   include/ilwisobjects/domain/thematicitem.h \
   include/ilwisobjects/domain/timeintervalitem.h \
   include/ilwisobjects/domain/valuedomain.h \
   include/ilwisobjects/geometry/coordinatesystem/boundsonlycoordinatesystem.h \
   include/ilwisobjects/geometry/coordinatesystem/conventionalcoordinatesystem.h \
   include/ilwisobjects/geometry/coordinatesystem/coordinatesystem.h \
   include/ilwisobjects/geometry/coordinatesystem/csytransform.h \
   include/ilwisobjects/geometry/coordinatesystem/ellipsoid.h \
   include/ilwisobjects/geometry/coordinatesystem/geodeticdatum.h \
   include/ilwisobjects/geometry/coordinatesystem/nullprojection.h \
   include/ilwisobjects/geometry/coordinatesystem/proj4parameters.h \
   include/ilwisobjects/geometry/coordinatesystem/projection.h \
   include/ilwisobjects/geometry/coordinatesystem/projectionfactory.h \
   include/ilwisobjects/geometry/coordinatesystem/projectionimplementation.h \
   include/ilwisobjects/geometry/georeference/controlpoint.h \
   include/ilwisobjects/geometry/georeference/cornersgeoreference.h \
   include/ilwisobjects/geometry/georeference/ctpgeoreference.h \
   include/ilwisobjects/geometry/georeference/georefadapter.h \
   include/ilwisobjects/geometry/georeference/georeference.h \
   include/ilwisobjects/geometry/georeference/georefimplementation.h \
   include/ilwisobjects/geometry/georeference/georefimplementationfactory.h \
   include/ilwisobjects/geometry/georeference/planarctpgeoreference.h \
   include/ilwisobjects/geometry/georeference/simpelgeoreference.h \
   include/ilwisobjects/geometry/georeference/undeterminedgeoreference.h \
   include/ilwisobjects/operation/classification/featurespace.h \
   include/ilwisobjects/operation/classification/sampleset.h \
   include/ilwisobjects/operation/classification/samplestatistics.h \
   include/ilwisobjects/operation/modeller/analysispattern.h \
   include/ilwisobjects/operation/modeller/applicationmodel.h \
   include/ilwisobjects/operation/modeller/conditionNode.h \
   include/ilwisobjects/operation/modeller/executionnode.h \
   include/ilwisobjects/operation/modeller/junctionNode.h \
   include/ilwisobjects/operation/modeller/model.h \
   include/ilwisobjects/operation/modeller/modellerfactory.h \
   include/ilwisobjects/operation/modeller/operationnode.h \
   include/ilwisobjects/operation/modeller/rangejunctionnode.h \
   include/ilwisobjects/operation/modeller/rangenode.h \
   include/ilwisobjects/operation/modeller/workflow.h \
   include/ilwisobjects/operation/modeller/workflowimplementation.h \
   include/ilwisobjects/operation/modeller/workflownode.h \
   include/ilwisobjects/operation/modeller/workflowparameter.h \
   include/ilwisobjects/operation/commandhandler.h \
   include/ilwisobjects/operation/ilwisoperation.h \
   include/ilwisobjects/operation/logicalexpressionparser.h \
   include/ilwisobjects/operation/numericoperation.h \
   include/ilwisobjects/operation/operation.h \
   include/ilwisobjects/operation/operationconnector.h \
   include/ilwisobjects/operation/operationExpression.h \
   include/ilwisobjects/operation/operationhelper.h \
   include/ilwisobjects/operation/operationhelperfeatures.h \
   include/ilwisobjects/operation/operationhelpergrid.h \
   include/ilwisobjects/operation/operationmetadata.h \
   include/ilwisobjects/operation/operationoverloads.h \
   include/ilwisobjects/operation/operationspec.h \
   include/ilwisobjects/operation/rasterfilter.h \
   include/ilwisobjects/operation/script.h \
   include/ilwisobjects/operation/symboltable.h \
   include/ilwisobjects/operation/workflowexecutionengine.h \
   include/ilwisobjects/representation/colorlookup.h \
   include/ilwisobjects/representation/continuouscolorlookup.h \
   include/ilwisobjects/representation/palettecolorlookup.h \
   include/ilwisobjects/representation/representation.h \
   include/ilwisobjects/representation/shapelookup.h \
   include/ilwisobjects/table/attributedefinition.h \
   include/ilwisobjects/table/attributetable.h \
   include/ilwisobjects/table/basetable.h \
   include/ilwisobjects/table/columndefinition.h \
   include/ilwisobjects/table/combinationmatrix.h \
   include/ilwisobjects/table/flattable.h \
   include/ilwisobjects/table/record.h \
   include/ilwisobjects/table/selectabletable.h \
   include/ilwisobjects/table/tabelinterface.h \
   include/ilwisobjects/table/table.h \
   include/ilwisobjects/table/tablemerger.h \
   include/ilwisobjects/table/tableselector.h \
   include/ilwisobjects/ilwisdata.h \
   include/ilwisobjects/ilwisobject.h \
   include/ilwisobjects/ilwisobjectconnector.h \
   include/ilwisobjects/ilwisobjectfactory.h \
   include/ilwisobjects/spinlock.h \
   include/util/boostext.h \
   include/util/box.h \
   include/util/bresenham.h \
   include/util/consoletranquilizer.h \
   include/util/containerstatistics.h \
   include/util/errmessages.h \
   include/util/geometries.h \
   include/util/ilwisconfiguration.h \
   include/util/ilwiscoordinate.h \
   include/util/juliantime.h \
   include/util/location.h \
   include/util/locker.h \
   include/util/mathhelper.h \
   include/util/memorymanager.h \
   include/util/natural_sorting.h \
   include/util/range.h \
   include/util/rowcol.h \
   include/util/size.h \
   include/util/supportlibraryloader.h \
   include/util/tranquilizer.h \
   include/util/tranquilizerfactory.h \
   include/util/valuerange.h \
   include/util/xmlstreamparser.h \
   include/util/xpathparser.h \
   include/abstractfactory.h \
   include/buildnumber.h \
   include/connectorfactory.h \
   include/connectorinterface.h \
   include/errorobject.h \
   include/factory.h \
   include/identity.h \
   include/identityinterface.h \
   include/ilwis.h \
   include/ilwiscontext.h \
   include/ilwisinterfaces.h \
   include/ilwistypes.h \
   include/internaldatabaseconnection.h \
   include/iooptions.h \
   include/issuelogger.h \
   include/kernel.h \
   include/kernel_global.h \
   include/module.h \
   include/oshelper.h \
   include/publicdatabase.h \
   include/user.h \
   include/version.h \
   source/geos/include/geos/platform.h.in \
   source/geos/include/geos/platform.h.vc \
   source/geos/include/geos/version.h.in \
   source/geos/include/geos/version.h.vc

DISTFILES += \
    source/geos/include/config.h.in

SOURCES += \
    source/catalog/catalog.cpp \
    source/catalog/catalogconnector.cpp \
    source/catalog/catalogexplorer.cpp \
    source/catalog/catalogexplorerworker.cpp \
    source/catalog/catalogquery.cpp \
    source/catalog/catalogview.cpp \
    source/catalog/dataformat.cpp \
    source/catalog/dataset.cpp \
    source/catalog/foldercatalogexplorer.cpp \
    source/catalog/mastercatalog.cpp \
    source/catalog/mastercatalogcache.cpp \
    source/catalog/resource.cpp \
#    source/geos/include/geos/algorithm/ConvexHull.inl \
#    source/geos/include/geos/geom/Coordinate.inl \
#    source/geos/include/geos/geom/CoordinateArraySequenceFactory.inl \
#    source/geos/include/geos/geom/Envelope.inl \
#    source/geos/include/geos/geom/GeometryCollection.inl \
#    source/geos/include/geos/geom/GeometryFactory.inl \
#    source/geos/include/geos/geom/LineSegment.inl \
#    source/geos/include/geos/geom/MultiLineString.inl \
#    source/geos/include/geos/geom/MultiPolygon.inl \
#    source/geos/include/geos/geom/PrecisionModel.inl \
#    source/geos/include/geos/geomgraph/DirectedEdge.inl \
#    source/geos/include/geos/geomgraph/GeometryGraph.inl \
#    source/geos/include/geos/io/ByteOrderDataInStream.inl \
#    source/geos/include/geos/io/WKTReader.inl \
#    source/geos/include/geos/noding/snapround/HotPixel.inl \
#    source/geos/include/geos/noding/MCIndexNoder.inl \
#    source/geos/include/geos/operation/overlay/MinimalEdgeRing.inl \
    source/geos/src/algorithm/distance/DiscreteHausdorffDistance.cpp \
    source/geos/src/algorithm/distance/DistanceToPoint.cpp \
    source/geos/src/algorithm/locate/IndexedPointInAreaLocator.cpp \
    source/geos/src/algorithm/locate/PointOnGeometryLocator.cpp \
    source/geos/src/algorithm/locate/SimplePointInAreaLocator.cpp \
    source/geos/src/algorithm/Angle.cpp \
    source/geos/src/algorithm/BoundaryNodeRule.cpp \
    source/geos/src/algorithm/Centroid.cpp \
    source/geos/src/algorithm/CentroidArea.cpp \
    source/geos/src/algorithm/CentroidLine.cpp \
    source/geos/src/algorithm/CentroidPoint.cpp \
    source/geos/src/algorithm/CGAlgorithms.cpp \
    source/geos/src/algorithm/ConvexHull.cpp \
    source/geos/src/algorithm/HCoordinate.cpp \
    source/geos/src/algorithm/InteriorPointArea.cpp \
    source/geos/src/algorithm/InteriorPointLine.cpp \
    source/geos/src/algorithm/InteriorPointPoint.cpp \
    source/geos/src/algorithm/LineIntersector.cpp \
    source/geos/src/algorithm/MCPointInRing.cpp \
    source/geos/src/algorithm/MinimumDiameter.cpp \
    source/geos/src/algorithm/NotRepresentableException.cpp \
    source/geos/src/algorithm/PointLocator.cpp \
    source/geos/src/algorithm/RayCrossingCounter.cpp \
    source/geos/src/algorithm/RobustDeterminant.cpp \
    source/geos/src/algorithm/SimplePointInRing.cpp \
    source/geos/src/algorithm/SIRtreePointInRing.cpp \
    source/geos/src/geom/prep/AbstractPreparedPolygonContains.cpp \
    source/geos/src/geom/prep/BasicPreparedGeometry.cpp \
    source/geos/src/geom/prep/PreparedGeometry.cpp \
    source/geos/src/geom/prep/PreparedGeometryFactory.cpp \
    source/geos/src/geom/prep/PreparedLineString.cpp \
    source/geos/src/geom/prep/PreparedLineStringIntersects.cpp \
    source/geos/src/geom/prep/PreparedPoint.cpp \
    source/geos/src/geom/prep/PreparedPolygon.cpp \
    source/geos/src/geom/prep/PreparedPolygonContains.cpp \
    source/geos/src/geom/prep/PreparedPolygonContainsProperly.cpp \
    source/geos/src/geom/prep/PreparedPolygonCovers.cpp \
    source/geos/src/geom/prep/PreparedPolygonIntersects.cpp \
    source/geos/src/geom/prep/PreparedPolygonPredicate.cpp \
    source/geos/src/geom/util/ComponentCoordinateExtracter.cpp \
    source/geos/src/geom/util/CoordinateOperation.cpp \
    source/geos/src/geom/util/GeometryCombiner.cpp \
    source/geos/src/geom/util/GeometryEditor.cpp \
    source/geos/src/geom/util/GeometryTransformer.cpp \
    source/geos/src/geom/util/LinearComponentExtracter.cpp \
    source/geos/src/geom/util/PointExtracter.cpp \
    source/geos/src/geom/util/PolygonExtracter.cpp \
    source/geos/src/geom/util/ShortCircuitedGeometryVisitor.cpp \
    source/geos/src/geom/util/SineStarFactory.cpp \
    source/geos/src/geom/Coordinate.cpp \
    source/geos/src/geom/CoordinateArraySequence.cpp \
    source/geos/src/geom/CoordinateArraySequenceFactory.cpp \
    source/geos/src/geom/CoordinateSequence.cpp \
    source/geos/src/geom/CoordinateSequenceFactory.cpp \
    source/geos/src/geom/Dimension.cpp \
    source/geos/src/geom/Envelope.cpp \
    source/geos/src/geom/Geometry.cpp \
    source/geos/src/geom/GeometryCollection.cpp \
    source/geos/src/geom/GeometryComponentFilter.cpp \
    source/geos/src/geom/GeometryFactory.cpp \
    source/geos/src/geom/GeometryList.cpp \
    source/geos/src/geom/IntersectionMatrix.cpp \
    source/geos/src/geom/LinearRing.cpp \
    source/geos/src/geom/LineSegment.cpp \
    source/geos/src/geom/LineString.cpp \
    source/geos/src/geom/Location.cpp \
    source/geos/src/geom/MultiLineString.cpp \
    source/geos/src/geom/MultiPoint.cpp \
    source/geos/src/geom/MultiPolygon.cpp \
    source/geos/src/geom/Point.cpp \
    source/geos/src/geom/Polygon.cpp \
    source/geos/src/geom/PrecisionModel.cpp \
    source/geos/src/geom/Triangle.cpp \
    source/geos/src/geomgraph/index/MonotoneChainEdge.cpp \
    source/geos/src/geomgraph/index/MonotoneChainIndexer.cpp \
    source/geos/src/geomgraph/index/SegmentIntersector.cpp \
    source/geos/src/geomgraph/index/SimpleEdgeSetIntersector.cpp \
    source/geos/src/geomgraph/index/SimpleMCSweepLineIntersector.cpp \
    source/geos/src/geomgraph/index/SimpleSweepLineIntersector.cpp \
    source/geos/src/geomgraph/index/SweepLineEvent.cpp \
    source/geos/src/geomgraph/index/SweepLineSegment.cpp \
    source/geos/src/geomgraph/Depth.cpp \
    source/geos/src/geomgraph/DirectedEdge.cpp \
    source/geos/src/geomgraph/DirectedEdgeStar.cpp \
    source/geos/src/geomgraph/EdgeEnd.cpp \
    source/geos/src/geomgraph/EdgeEndStar.cpp \
    source/geos/src/geomgraph/EdgeGeomGraph.cpp \
    source/geos/src/geomgraph/EdgeIntersectionList.cpp \
    source/geos/src/geomgraph/EdgeList.cpp \
    source/geos/src/geomgraph/EdgeNodingValidator.cpp \
    source/geos/src/geomgraph/EdgeRing.cpp \
    source/geos/src/geomgraph/GeometryGraph.cpp \
    source/geos/src/geomgraph/GraphComponent.cpp \
    source/geos/src/geomgraph/Label.cpp \
    source/geos/src/geomgraph/NodeFactory.cpp \
    source/geos/src/geomgraph/NodeGeomGraph.cpp \
    source/geos/src/geomgraph/NodeMap.cpp \
    source/geos/src/geomgraph/PlanarGraphGG.cpp \
    source/geos/src/geomgraph/Position.cpp \
    source/geos/src/geomgraph/Quadrant.cpp \
    source/geos/src/geomgraph/TopologyLocation.cpp \
    source/geos/src/index/bintree/Bintree.cpp \
    source/geos/src/index/bintree/IntervalBinTree.cpp \
    source/geos/src/index/bintree/KeyBinTree.cpp \
    source/geos/src/index/bintree/NodeBaseBinTree.cpp \
    source/geos/src/index/bintree/NodeBinTree.cpp \
    source/geos/src/index/bintree/RootBinTree.cpp \
    source/geos/src/index/chain/MonotoneChain.cpp \
    source/geos/src/index/chain/MonotoneChainBuilder.cpp \
    source/geos/src/index/chain/MonotoneChainOverlapAction.cpp \
    source/geos/src/index/chain/MonotoneChainSelectAction.cpp \
    source/geos/src/index/intervalrtree/IntervalRTreeBranchNode.cpp \
    source/geos/src/index/intervalrtree/IntervalRTreeLeafNode.cpp \
    source/geos/src/index/intervalrtree/IntervalRTreeNode.cpp \
    source/geos/src/index/intervalrtree/SortedPackedIntervalRTree.cpp \
    source/geos/src/index/quadtree/DoubleBits.cpp \
    source/geos/src/index/quadtree/IntervalSize.cpp \
    source/geos/src/index/quadtree/KeyQuadTree.cpp \
    source/geos/src/index/quadtree/NodeBaseQuadTree.cpp \
    source/geos/src/index/quadtree/NodeQuadTree.cpp \
    source/geos/src/index/quadtree/Quadtree.cpp \
    source/geos/src/index/quadtree/RootQuadTree.cpp \
    source/geos/src/index/strtree/AbstractNode.cpp \
    source/geos/src/index/strtree/AbstractSTRtree.cpp \
    source/geos/src/index/strtree/IntervalStree.cpp \
    source/geos/src/index/strtree/ItemBoundable.cpp \
    source/geos/src/index/strtree/SIRtree.cpp \
    source/geos/src/index/strtree/STRtree.cpp \
    source/geos/src/index/sweepline/SweepLineEventSL.cpp \
    source/geos/src/index/sweepline/SweepLineIndex.cpp \
    source/geos/src/index/sweepline/SweepLineInterval.cpp \
    source/geos/src/io/ByteOrderDataInStream.cpp \
    source/geos/src/io/ByteOrderValues.cpp \
    source/geos/src/io/CLocalizer.cpp \
    source/geos/src/io/ParseException.cpp \
    source/geos/src/io/StringTokenizer.cpp \
    source/geos/src/io/Unload.cpp \
    source/geos/src/io/WKBReader.cpp \
    source/geos/src/io/WKBWriter.cpp \
    source/geos/src/io/WKTReader.cpp \
    source/geos/src/io/WKTWriter.cpp \
    source/geos/src/io/Writer.cpp \
    source/geos/src/linearref/ExtractLineByLocation.cpp \
    source/geos/src/linearref/LengthIndexedLine.cpp \
    source/geos/src/linearref/LengthIndexOfPoint.cpp \
    source/geos/src/linearref/LengthLocationMap.cpp \
    source/geos/src/linearref/LinearGeometryBuilder.cpp \
    source/geos/src/linearref/LinearIterator.cpp \
    source/geos/src/linearref/LinearLocation.cpp \
    source/geos/src/linearref/LocationIndexOfLine.cpp \
    source/geos/src/linearref/LocationIndexOfPoint.cpp \
    source/geos/src/noding/snapround/HotPixel.cpp \
    source/geos/src/noding/snapround/MCIndexPointSnapper.cpp \
    source/geos/src/noding/snapround/MCIndexSnapRounder.cpp \
    source/geos/src/noding/snapround/SimpleSnapRounder.cpp \
    source/geos/src/noding/BasicSegmentString.cpp \
    source/geos/src/noding/FastNodingValidator.cpp \
    source/geos/src/noding/FastSegmentSetIntersectionFinder.cpp \
    source/geos/src/noding/GeometryNoder.cpp \
    source/geos/src/noding/IntersectionAdder.cpp \
    source/geos/src/noding/IntersectionFinderAdder.cpp \
    source/geos/src/noding/IteratedNoder.cpp \
    source/geos/src/noding/MCIndexNoder.cpp \
    source/geos/src/noding/MCIndexSegmentSetMutualIntersector.cpp \
    source/geos/src/noding/NodedSegmentString.cpp \
    source/geos/src/noding/NodingValidator.cpp \
    source/geos/src/noding/Octant.cpp \
    source/geos/src/noding/OrientedCoordinateArray.cpp \
    source/geos/src/noding/ScaledNoder.cpp \
    source/geos/src/noding/SegmentIntersectionDetector.cpp \
    source/geos/src/noding/SegmentNode.cpp \
    source/geos/src/noding/SegmentNodeList.cpp \
    source/geos/src/noding/SegmentString.cpp \
    source/geos/src/noding/SegmentStringUtil.cpp \
    source/geos/src/noding/SimpleNoder.cpp \
    source/geos/src/noding/SingleInteriorIntersectionFinder.cpp \
    source/geos/src/operation/buffer/BufferBuilder.cpp \
    source/geos/src/operation/buffer/BufferInputLineSimplifier.cpp \
    source/geos/src/operation/buffer/BufferOp.cpp \
    source/geos/src/operation/buffer/BufferParameters.cpp \
    source/geos/src/operation/buffer/BufferSubgraph.cpp \
    source/geos/src/operation/buffer/OffsetCurveBuilder.cpp \
    source/geos/src/operation/buffer/OffsetCurveSetBuilder.cpp \
    source/geos/src/operation/buffer/OffsetSegmentGenerator.cpp \
    source/geos/src/operation/buffer/RightmostEdgeFinder.cpp \
    source/geos/src/operation/buffer/SubgraphDepthLocater.cpp \
    source/geos/src/operation/distance/ConnectedElementLocationFilter.cpp \
    source/geos/src/operation/distance/ConnectedElementPointFilter.cpp \
    source/geos/src/operation/distance/DistanceOp.cpp \
    source/geos/src/operation/distance/GeometryLocation.cpp \
    source/geos/src/operation/intersection/Rectangle.cpp \
    source/geos/src/operation/intersection/RectangleIntersection.cpp \
    source/geos/src/operation/intersection/RectangleIntersectionBuilder.cpp \
    source/geos/src/operation/linemerge/EdgeString.cpp \
    source/geos/src/operation/linemerge/LineMergeDirectedEdge.cpp \
    source/geos/src/operation/linemerge/LineMergeEdge.cpp \
    source/geos/src/operation/linemerge/LineMergeGraph.cpp \
    source/geos/src/operation/linemerge/LineMerger.cpp \
    source/geos/src/operation/linemerge/LineSequencer.cpp \
    source/geos/src/operation/overlay/snap/GeometrySnapper.cpp \
    source/geos/src/operation/overlay/snap/LineStringSnapper.cpp \
    source/geos/src/operation/overlay/snap/SnapIfNeededOverlayOp.cpp \
    source/geos/src/operation/overlay/snap/SnapOverlayOp.cpp \
    source/geos/src/operation/overlay/validate/FuzzyPointLocator.cpp \
    source/geos/src/operation/overlay/validate/OffsetPointGenerator.cpp \
    source/geos/src/operation/overlay/validate/OverlayResultValidator.cpp \
    source/geos/src/operation/overlay/EdgeSetNoder.cpp \
    source/geos/src/operation/overlay/ElevationMatrix.cpp \
    source/geos/src/operation/overlay/ElevationMatrixCell.cpp \
    source/geos/src/operation/overlay/LineBuilder.cpp \
    source/geos/src/operation/overlay/MaximalEdgeRing.cpp \
    source/geos/src/operation/overlay/MinimalEdgeRing.cpp \
    source/geos/src/operation/overlay/OverlayNodeFactory.cpp \
    source/geos/src/operation/overlay/OverlayOp.cpp \
    source/geos/src/operation/overlay/PointBuilder.cpp \
    source/geos/src/operation/overlay/PolygonBuilder.cpp \
    source/geos/src/operation/polygonize/EdgeRingPologonize.cpp \
    source/geos/src/operation/polygonize/PolygonizeDirectedEdge.cpp \
    source/geos/src/operation/polygonize/PolygonizeEdge.cpp \
    source/geos/src/operation/polygonize/PolygonizeGraph.cpp \
    source/geos/src/operation/polygonize/Polygonizer.cpp \
    source/geos/src/operation/predicate/RectangleContains.cpp \
    source/geos/src/operation/predicate/RectangleIntersects.cpp \
    source/geos/src/operation/predicate/SegmentIntersectionTester.cpp \
    source/geos/src/operation/relate/EdgeEndBuilder.cpp \
    source/geos/src/operation/relate/EdgeEndBundle.cpp \
    source/geos/src/operation/relate/EdgeEndBundleStar.cpp \
    source/geos/src/operation/relate/RelateComputer.cpp \
    source/geos/src/operation/relate/RelateNode.cpp \
    source/geos/src/operation/relate/RelateNodeFactory.cpp \
    source/geos/src/operation/relate/RelateNodeGraph.cpp \
    source/geos/src/operation/relate/RelateOp.cpp \
    source/geos/src/operation/sharedpaths/SharedPathsOp.cpp \
    source/geos/src/operation/union/CascadedPolygonUnion.cpp \
    source/geos/src/operation/union/CascadedUnion.cpp \
    source/geos/src/operation/union/PointGeometryUnion.cpp \
    source/geos/src/operation/union/UnaryUnionOp.cpp \
    source/geos/src/operation/valid/ConnectedInteriorTester.cpp \
    source/geos/src/operation/valid/ConsistentAreaTester.cpp \
    source/geos/src/operation/valid/IndexedNestedRingTester.cpp \
    source/geos/src/operation/valid/IsValidOp.cpp \
    source/geos/src/operation/valid/QuadtreeNestedRingTester.cpp \
    source/geos/src/operation/valid/RepeatedPointTester.cpp \
    source/geos/src/operation/valid/SimpleNestedRingTester.cpp \
    source/geos/src/operation/valid/SweeplineNestedRingTester.cpp \
    source/geos/src/operation/valid/TopologyValidationError.cpp \
    source/geos/src/operation/GeometryGraphOperation.cpp \
    source/geos/src/operation/IsSimpleOp.cpp \
    source/geos/src/planargraph/algorithm/ConnectedSubgraphFinder.cpp \
    source/geos/src/planargraph/DirectedEdgePlanarGraph.cpp \
    source/geos/src/planargraph/DirectedEdgeStarPlanarGraph.cpp \
    source/geos/src/planargraph/EdgePlanarGraph.cpp \
    source/geos/src/planargraph/NodeMapPlanarGraph.cpp \
    source/geos/src/planargraph/NodePlanarGraph.cpp \
    source/geos/src/planargraph/PlanarGraph.cpp \
    source/geos/src/planargraph/Subgraph.cpp \
    source/geos/src/precision/CommonBits.cpp \
    source/geos/src/precision/CommonBitsOp.cpp \
    source/geos/src/precision/CommonBitsRemover.cpp \
    source/geos/src/precision/EnhancedPrecisionOp.cpp \
    source/geos/src/precision/GeometryPrecisionReducer.cpp \
    source/geos/src/precision/PrecisionReducerCoordinateOperation.cpp \
    source/geos/src/precision/SimpleGeometryPrecisionReducer.cpp \
    source/geos/src/simplify/DouglasPeuckerLineSimplifier.cpp \
    source/geos/src/simplify/DouglasPeuckerSimplifier.cpp \
    source/geos/src/simplify/LineSegmentIndex.cpp \
    source/geos/src/simplify/TaggedLineSegment.cpp \
    source/geos/src/simplify/TaggedLinesSimplifier.cpp \
    source/geos/src/simplify/TaggedLineString.cpp \
    source/geos/src/simplify/TaggedLineStringSimplifier.cpp \
    source/geos/src/simplify/TopologyPreservingSimplifier.cpp \
    source/geos/src/triangulate/quadedge/LastFoundQuadEdgeLocator.cpp \
    source/geos/src/triangulate/quadedge/LocateFailureException.cpp \
    source/geos/src/triangulate/quadedge/QuadEdge.cpp \
    source/geos/src/triangulate/quadedge/QuadEdgeLocator.cpp \
    source/geos/src/triangulate/quadedge/QuadEdgeSubdivision.cpp \
    source/geos/src/triangulate/quadedge/TrianglePredicate.cpp \
    source/geos/src/triangulate/quadedge/TriangleVisitor.cpp \
    source/geos/src/triangulate/quadedge/Vertex.cpp \
    source/geos/src/triangulate/DelaunayTriangulationBuilder.cpp \
    source/geos/src/triangulate/IncrementalDelaunayTriangulator.cpp \
    source/geos/src/triangulate/VoronoiDiagramBuilder.cpp \
    source/geos/src/util/Assert.cpp \
    source/geos/src/util/GeometricShapeFactory.cpp \
    source/geos/src/util/Interrupt.cpp \
    source/geos/src/util/math.cpp \
    source/geos/src/util/Profiler.cpp \
    source/geos/src/inlines.cpp \
    source/ilwisobjects/coverage/blockiterator.cpp \
    source/ilwisobjects/coverage/coverage.cpp \
    source/ilwisobjects/coverage/feature.cpp \
    source/ilwisobjects/coverage/featurecoverage.cpp \
    source/ilwisobjects/coverage/featurefactory.cpp \
    source/ilwisobjects/coverage/featureiterator.cpp \
    source/ilwisobjects/coverage/geometryhelper.cpp \
    source/ilwisobjects/coverage/grid.cpp \
    source/ilwisobjects/coverage/indexslicer.cpp \
    source/ilwisobjects/coverage/pixeliterator.cpp \
    source/ilwisobjects/coverage/rastercoverage.cpp \
    source/ilwisobjects/coverage/rasterinterpolator.cpp \
    source/ilwisobjects/coverage/vertexiterator.cpp \
    source/ilwisobjects/domain/colordomain.cpp \
    source/ilwisobjects/domain/coloritem.cpp \
    source/ilwisobjects/domain/colorrange.cpp \
    source/ilwisobjects/domain/coordinatedomain.cpp \
    source/ilwisobjects/domain/datadefinition.cpp \
    source/ilwisobjects/domain/domain.cpp \
    source/ilwisobjects/domain/domainhelper.cpp \
    source/ilwisobjects/domain/domainmerger.cpp \
    source/ilwisobjects/domain/identifieritem.cpp \
    source/ilwisobjects/domain/identifierrange.cpp \
    source/ilwisobjects/domain/interval.cpp \
    source/ilwisobjects/domain/intervalrange.cpp \
    source/ilwisobjects/domain/itemrange.cpp \
    source/ilwisobjects/domain/numericdomain.cpp \
    source/ilwisobjects/domain/numericrange.cpp \
    source/ilwisobjects/domain/textdomain.cpp \
    source/ilwisobjects/domain/thematicitem.cpp \
    source/ilwisobjects/domain/timeintervalitem.cpp \
    source/ilwisobjects/geometry/coordinatesystem/boundsonlycoordinatesystem.cpp \
    source/ilwisobjects/geometry/coordinatesystem/conventionalcoordinatesystem.cpp \
    source/ilwisobjects/geometry/coordinatesystem/coordinatesystem.cpp \
    source/ilwisobjects/geometry/coordinatesystem/csytransform.cpp \
    source/ilwisobjects/geometry/coordinatesystem/ellipsoid.cpp \
    source/ilwisobjects/geometry/coordinatesystem/geodeticdatum.cpp \
    source/ilwisobjects/geometry/coordinatesystem/proj4parameters.cpp \
    source/ilwisobjects/geometry/coordinatesystem/projection.cpp \
    source/ilwisobjects/geometry/coordinatesystem/projectionimplementation.cpp \
    source/ilwisobjects/geometry/georeference/controlpoint.cpp \
    source/ilwisobjects/geometry/georeference/cornersgeoreference.cpp \
    source/ilwisobjects/geometry/georeference/ctpgeoreference.cpp \
    source/ilwisobjects/geometry/georeference/georefadapter.cpp \
    source/ilwisobjects/geometry/georeference/georeference.cpp \
    source/ilwisobjects/geometry/georeference/georefimplementation.cpp \
    source/ilwisobjects/geometry/georeference/georefimplementationfactory.cpp \
    source/ilwisobjects/geometry/georeference/planarctpgeoreference.cpp \
    source/ilwisobjects/geometry/georeference/simpelgeoreference.cpp \
    source/ilwisobjects/geometry/georeference/undeterminedgeoreference.cpp \
    source/ilwisobjects/operation/classification/featurespace.cpp \
    source/ilwisobjects/operation/classification/sampleset.cpp \
    source/ilwisobjects/operation/classification/samplestatistics.cpp \
    source/ilwisobjects/operation/modeller/analysispattern.cpp \
    source/ilwisobjects/operation/modeller/applicationmodel.cpp \
    source/ilwisobjects/operation/modeller/conditionNode.cpp \
    source/ilwisobjects/operation/modeller/executionnode.cpp \
    source/ilwisobjects/operation/modeller/junctionNode.cpp \
    source/ilwisobjects/operation/modeller/model.cpp \
    source/ilwisobjects/operation/modeller/modellerfactory.cpp \
    source/ilwisobjects/operation/modeller/operationnode.cpp \
    source/ilwisobjects/operation/modeller/rangejunctionnode.cpp \
    source/ilwisobjects/operation/modeller/rangenode.cpp \
    source/ilwisobjects/operation/modeller/workflow.cpp \
    source/ilwisobjects/operation/modeller/workflowimplementation.cpp \
    source/ilwisobjects/operation/modeller/workflownode.cpp \
    source/ilwisobjects/operation/modeller/workflowparameter.cpp \
    source/ilwisobjects/operation/commandhandler.cpp \
    source/ilwisobjects/operation/logicalexpressionparser.cpp \
    source/ilwisobjects/operation/numericoperation.cpp \
    source/ilwisobjects/operation/operation.cpp \
    source/ilwisobjects/operation/operationExpression.cpp \
    source/ilwisobjects/operation/operationhelper.cpp \
    source/ilwisobjects/operation/operationhelperfeatures.cpp \
    source/ilwisobjects/operation/operationhelpergrid.cpp \
    source/ilwisobjects/operation/operationmetadata.cpp \
    source/ilwisobjects/operation/operationoverloads.cpp \
    source/ilwisobjects/operation/rasterfilter.cpp \
    source/ilwisobjects/operation/script.cpp \
    source/ilwisobjects/operation/symboltable.cpp \
    source/ilwisobjects/operation/workflowexecutionengine.cpp \
    source/ilwisobjects/representation/colorlookup.cpp \
    source/ilwisobjects/representation/continuouscolorlookup.cpp \
    source/ilwisobjects/representation/palettecolorlookup.cpp \
    source/ilwisobjects/representation/representation.cpp \
    source/ilwisobjects/representation/shapelookup.cpp \
    source/ilwisobjects/table/attributedefinition.cpp \
    source/ilwisobjects/table/attributetable.cpp \
    source/ilwisobjects/table/basetable.cpp \
    source/ilwisobjects/table/columndefinition.cpp \
    source/ilwisobjects/table/combinationmatrix.cpp \
    source/ilwisobjects/table/flattable.cpp \
    source/ilwisobjects/table/record.cpp \
    source/ilwisobjects/table/selectabletable.cpp \
    source/ilwisobjects/table/tablemerger.cpp \
    source/ilwisobjects/table/tableselector.cpp \
    source/ilwisobjects/ilwisobject.cpp \
    source/ilwisobjects/ilwisobjectconnector.cpp \
    source/ilwisobjects/ilwisobjectfactory.cpp \
    source/util/bresenham.cpp \
    source/util/consoletranquilizer.cpp \
    source/util/ilwisconfiguration.cpp \
    source/util/ilwiscoordinate.cpp \
    source/util/juliantime.cpp \
    source/util/locker.cpp \
    source/util/mathhelper.cpp \
    source/util/range.cpp \
    source/util/rowcol.cpp \
    source/util/supportlibraryloader.cpp \
    source/util/tranquilizer.cpp \
    source/util/tranquilizerfactory.cpp \
    source/util/xmlstreamparser.cpp \
    source/abstractfactory.cpp \
    source/connectorfactory.cpp \
    source/errorobject.cpp \
    source/identity.cpp \
    source/identityinterface.cpp \
    source/ilwiscontext.cpp \
    source/ilwistypes.cpp \
    source/internaldatabaseconnection.cpp \
    source/iooptions.cpp \
    source/issuelogger.cpp \
    source/kernel.cpp \
    source/module.cpp \
    source/oshelper.cpp \
    source/publicdatabase.cpp \
    source/user.cpp \
    source/version.cpp

